networks:
  proxynet:
    name: sf-website-development
    external: true

services:
  playwright-test:
    container_name: apostrophe-playwright-test
    build:
      context: ./website/e2e
      dockerfile: Dockerfile
    environment:
      - BASE_URL=http://apostrophe:3000
      - CI=true
    networks:
      - proxynet
    volumes:
      - ./e2e-snapshots-main:/e2e/tests/screenshot-test.spec.js-snapshots
      - ./e2e-snapshots-results:/e2e/playwright-report
      - ./e2e-test-results:/e2e/test-results

