networks:
  proxynet:
    name: sf-website-development

services:
  minio:
    image: minio/minio:latest
    container_name: apostrophe-minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    volumes:
      - minio-data:/data
    command: server --console-address :9001 /data
    networks:
      - proxynet
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 5s
      retries: 3

  # MinIO setup helper - creates bucket and configures policies
  minio-setup:
    image: minio/mc
    container_name: apostrophe-minio-setup
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc config host add myminio http://minio:9000 minio minio123;
      /usr/bin/mc mb myminio/apostrophe-test-bucket --ignore-existing;
      /usr/bin/mc anonymous set download myminio/apostrophe-test-bucket;
      exit 0;
      "
    networks:
      - proxynet

  # Apostrophe CMS web application
  apostrophe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: apostrophe-cms
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - APOS_MONGODB_URI=mongodb://mongodb:27017/apostrophe
      - SESSION_SECRET=change_this_to_a_secure_secret
      # S3 settings for MinIO
      - APOS_S3_BUCKET=${APOS_S3_BUCKET:-apostrophe-test-bucket}
      - APOS_S3_REGION=${APOS_S3_REGION:-us-east-1}
      - APOS_S3_KEY=${APOS_S3_KEY:-minio}
      - APOS_S3_SECRET=${APOS_S3_SECRET:-minio123}
      # MinIO endpoint
      - APOS_S3_ENDPOINT=${APOS_S3_ENDPOINT:-http://minio:9000}
      - APOS_S3_PATH_STYLE=${APOS_S3_PATH_STYLE:-true}
      # Fix for URL generation in HTML
      - APOS_UPLOADS_URL=${APOS_UPLOADS_URL:-http://minio:9000/apostrophe-test-bucket}
      # Public URL for browser access (must use localhost, not container name)
      - APOS_UPLOADS_PUBLIC_URL=${APOS_UPLOADS_PUBLIC_URL:-http://localhost:9000/apostrophe-test-bucket}
      # CDN setting loaded from .env file
      - APOS_CDN_URL=${APOS_CDN_URL:-}
      - APOS_CDN_ENABLED=${APOS_CDN_ENABLED:-false}

    command: ["npm", "start"]
    depends_on:
      - mongodb
      - minio
      - minio-setup
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3000/",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - proxynet
    # Command to run tests: docker compose run --rm apostrophe npm run test
    # Command to run tests with coverage: docker compose run --rm apostrophe npm run test -- --coverage

  # MongoDB database
  mongodb:
    image: mongo:7.0
    container_name: apostrophe-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --quiet --logpath /dev/null
    restart: unless-stopped
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - proxynet

  # Mongo Express for database management (optional, development only)
  mongo-express:
    image: mongo-express:latest
    container_name: apostrophe-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - proxynet

  # Redis for caching (optional, but recommended for production)
  redis:
    image: redis:7-alpine
    container_name: apostrophe-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - proxynet

volumes:
  mongodb_data:
  redis_data:
  minio-data:
