

services:
  apostrophe:
    # In development mode, use nodemon instead of normal start
    command: npm run dev
    user: root
    environment:
      - NODE_ENV=development
    ports:
      - "9229:9229"  # For Node.js debugging
    volumes:
      - ./website:/app
      - /app/node_modules

  # Uncomment to enable Adminer for database management 
  # adminer:
  #   image: adminer:latest
  #   container_name: apostrophe-adminer
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - mongodb
  #   restart: unless-stopped 