networks:
  my-proxy-net:
    name: sf-website-development
    external: true

services:
  playwright-test:
    container_name: apostrophe-playwright-test
    build:
      context: ./e2e
      dockerfile: Dockerfile
    depends_on:
      - apostrophe
    environment:
      - BASE_URL=http://apostrophe:3000
      - WAIT_HOSTS=apostrophe:3000
      - WAIT_TIMEOUT=60
    networks:
      - my-proxy-net
    volumes:
      - ./e2e/tests/screenshot-test.spec.js-snapshots:/e2e/tests/screenshot-test.spec.js-snapshots
      - ./e2e/playwright-report:/e2e/playwright-report
      - ./e2e/test-results:/e2e/test-results
