[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.production"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
numReplicas = 1

[deploy.envs]
NODE_ENV = "production" 