/*
 * Client-side access to shared constants.
 * IMPORTANT: This file is auto-generated from the server-side constants.
 * DO NOT EDIT THIS FILE DIRECTLY - modify the server-side constants instead.
 */

// Direct export of constants for import { STANDARD_FORM_FIELD_NAMES } from '...'
export const STANDARD_FORM_FIELD_NAMES = {
  FULL_NAME: 'full-name',
  EMAIL_ADDRESS: 'email-address',
  PHONE_NUMBER: 'phone-number'
};

// Default export function for backwards compatibility
export default () => {
  return {
    STANDARD_FORM_FIELD_NAMES,
  };
};
