// Mock dependencies
const fs = require('fs');
jest.mock('fs');

jest.mock('path', () => ({
  resolve: jest.fn().mockImplementation((_, filePath) => filePath),
}));

// Mock for server constants module - this is for the success test
const mockServerModule = {
  init: jest.fn().mockImplementation((self) => {
    self.STANDARD_FORM_FIELD_NAMES = {
      firstName: 'firstName',
      lastName: 'lastName',
      email: 'email',
    };
  }),
};

// Register the success mock
jest.mock('../modules/shared-constants/index.js', () => mockServerModule);

describe('generate-constants.js', () => {
  // Reset mocks before each test
  beforeEach(() => {
    jest.clearAllMocks();
    // Clear the script from require cache
    delete require.cache[require.resolve('./generate-constants')];
  });

  test('successfully generates client-side constants', () => {
    // Run the script
    require('./generate-constants');

    // Check that the server module's init function was called
    expect(mockServerModule.init).toHaveBeenCalled();

    // Check that fs.writeFileSync was called with the right arguments
    expect(fs.writeFileSync).toHaveBeenCalledTimes(1);
    expect(fs.writeFileSync).toHaveBeenCalledWith(
      '../modules/shared-constants/ui/src/index.js',
      expect.stringContaining('STANDARD_FORM_FIELD_NAMES'),
    );

    // Check content of generated file
    const fileContent = fs.writeFileSync.mock.calls[0][1];
    expect(fileContent).toContain('firstName');
    expect(fileContent).toContain('lastName');
    expect(fileContent).toContain('email');
    expect(fileContent).toContain('DO NOT EDIT THIS FILE DIRECTLY');
  });
});

// Separate test for error handling using a completely different approach
test('handles errors properly', () => {
  /*
   * Mock global functions using spies instead of direct replacement
   * This avoids the console statement linter errors
   */
  const errorSpy = jest
    .spyOn(console, 'error')
    .mockImplementation(() => undefined);
  const exitSpy = jest
    .spyOn(process, 'exit')
    .mockImplementation(() => undefined);

  try {
    // Force the server module's init to throw an error
    mockServerModule.init.mockImplementationOnce(() => {
      throw new Error('Test error');
    });

    // Clear require cache to ensure script runs again
    jest.resetModules();
    delete require.cache[require.resolve('./generate-constants')];

    // Run the script which should now encounter the error
    require('./generate-constants');

    // Check that error handling was triggered
    expect(errorSpy).toHaveBeenCalledWith(
      'Error generating client-side constants:',
      expect.any(Error),
    );
    expect(exitSpy).toHaveBeenCalledWith(1);
  } finally {
    // Restore spies
    errorSpy.mockRestore();
    exitSpy.mockRestore();
  }
});
