name: Code Quality

on:
  pull_request:
    types: [synchronize, opened, reopened]

jobs:
  docker-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
  
  javascript-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'
          cache: 'npm'
          cache-dependency-path: website/package.json
      
      - name: Install dependencies
        run: cd website && npm ci
        
      - name: Run ESLint
        uses: eslint/eslint-action@v3.0.0
        with:
          workdir: website
        
  security-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: apostrophe-cms:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
        
      - name: Run Docker Scout scan
        uses: docker/scout-action@v1
        with:
          command: cves
          image: apostrophe-cms:test
          sarif-file: docker-scan-results.sarif
          
      - name: Upload scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: docker-scan-results.sarif
          category: docker-scout 