name: 'Deploy to Railway'

permissions:
  contents: read

on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:
    inputs:
      deploy-env:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
        - Development
        - Staging
        - Production
        default: Development
      restore-db:
        description: 'Restore database to original state (Reset database for Development and restore anon dump for Staging and Production)'
        required: false
        type: boolean
        default: false

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    environment: Development
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/snf-website-apostrophe-cms:build
          cache-from: type=gha
          cache-to: type=gha,mode=max
          

  deploy-to-railway:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    environment: Development
    env:
      SVC_ID: my-service-id
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_GITHUB_ACTIONS }}
    steps:
      - name: Apply new image to Railway
        run:  railway up --service=${{ env.SVC_ID  }}
          

