name: 'Deploy to Railway'

on:
  push:
    branches:
      - main
      - 'releases/**'

  workflow_dispatch:
    inputs:
      deploy-env:
        description: 'Environment to deploy'
        required: true
        type: choice
        options:
        - Development
        - Staging
        - Production
        default: Development
      restore-db:
        description: 'Restore database to original state (Reset database for Development and restore anon dump for Test and Pre-prod)'
        required: false
        type: boolean
        default: false

jobs:
  deploy-to-railway:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Do nothing
        run: echo "Do nothing here"

