name: '[Release] Init release (create release branch for code freeze)'

on:
  workflow_dispatch:
   
jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create release branch
        uses: peterjgrainger/action-create-branch@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: releases/v.${{ inputs.release-version }}
          sha: '${{ github.sha }}'
