name: Update Snapshots

on:
  workflow_dispatch:

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker starts services
        run: docker compose up -d --build

      - name: Wait for services to start
        run: sleep 15

      - name: Run as root to install system deps
        run: docker compose exec --user root apostrophe npx playwright install-deps

      - name: Install Playwright Browsers
        run: docker compose exec apostrophe npx playwright install

      - name: Run Playwright tests with snapshot update
        run: docker compose exec apostrophe sh -c "npm run test:e2e -- --update-snapshots"
        continue-on-error: true

      - name: Ensure snapshot directory exists
        run: mkdir -p website/e2e/

      - name: Copy snapshots from container
        run: docker compose cp apostrophe:/app/e2e/screenshot-test.spec.js-snapshots website/e2e/

      - name: Upload snapshots as artifact
        uses: actions/upload-artifact@v4
        with:
          name: playwright-snapshots
          path: website/e2e/screenshot-test.spec.js-snapshots
          overwrite: true
          retention-days: 20
